framework:
    validation:
        # Enables validator auto-mapping support
        auto_mapping:
            App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false