services:
  php:
    build:
      context: .
      target: frankenphp_dev
    restart: unless-stopped
    depends_on:
      - database
    environment:
     # Disable Mercure
      MERCURE_PUBLISHER_JWT_KEY: disabled
      MERCURE_SUBSCRIBER_JWT_KEY: disabled
      # Your application settings
      APP_ENV: dev
      
      # PostgreSQL connection string
      
      DATABASE_URL: postgresql://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-password}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
    volumes:
      - ./:/app
      - ./frankenphp/custom-Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-symfony}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  database_data: