homepage:
  path: /
  controller: App\Controller\IndexController::index

app_article_index:
  path: /article
  controller: App\Controller\ArticleController::index
  methods: [GET]

app_article_new:
  path: /article/new
  controller: App\Controller\ArticleController::new
  methods: [GET, POST]

app_article_show:
  path: /article/{id}
  controller: App\Controller\ArticleController::show
  methods: [GET]

app_article_edit:
  path: /article/{id}/edit
  controller: App\Controller\ArticleController::edit
  methods: [GET, POST]

app_article_delete:
  path: /article/{id}
  controller: App\Controller\ArticleController::delete
  methods: [POST]